# Docker compose example for Dokuwiki (used for development)
services:
  dokuwiki:
    hostname: dokuwiki
    image: upb-cs-ocw/dokuwiki:latest
    user: "app:app"
    restart: no
    ports:
      - "8080:8080"
    environment:
      PHP_TIMEZONE: Europe/Bucharest
      DOKUWIKI_ADMIN_USER: admin
      DOKUWIKI_ADMIN_PASSWORD: admin123
      DOKUWIKI_DEMO_INSTALL: yes
    volumes:
      - ${DOKUWIKI_STORAGE_DIR:-./tmp}:/storage
      # uncomment for template development:
      #- ./dokuwiki/tpl/arctic-cs/:/storage/lib/tpl/arctic-cs/:ro
