; Farm config created by the farmer plugin

[base]
# Note: this will be replaced by ENV
farmhost = ""
basedomain = ""
farmdir = "/storage/farm/"

[notfound]
show = "error404"
url = ""

[inherit]
main = 1
acronyms = 1
entities = 1
interwiki = 1
license = 1
mime = 1
scheme = 1
smileys = 1
wordblock = 1
users = 1
plugins = 1
userstyle = 1
userscript = 1
styleini = 1

